import {writable} from "svelte/store";

export const firstLoad=writable(false);

export const totalGenerations=writable(0);

export const loading=writable(false);
export const colorStatuses=writable(["nothing","nothing","nothing","nothing","nothing"]);

export const placeholders = writable([
    "Enchanted Moonlit Forest",
    "70s Vinyl Record Shop",
    "Santorini Summer",
    "Cyberpunk Tokyo",
    "Alice's Wonderland",
    "Monet's Garden",
    "Savannah Sunset",
    "Autumn Bakery",
    "Rainforest Retreat",
    "Appalachian Cabin",
    "Rainy Coffee Shop",
    "Martian Colony",
    "Film Noir Setting",
    "Scandinavian Winter",
    "Old Hollywood",
    "Moroccan Spice Bazaar",
    "Grand Library",
    "Mayan Jungle Ruins",
    "Atlantis Undersea",
    "Victorian Steampunk",
    "Midnight Arctic",
    "Bohemian Art Studio",
    "Rainforest Cafe",
    "Silk Road Caravan",
    "Southern Gothic Mansion",
    "Japanese Cherry Blossom Garden",
    "1920s Jazz Club",
    "Pacific Northwest Road Trip",
    "Abandoned Space Station",
    "Prohibition Era Speakeasy",
    "Modern Miami Beach",
    "Dystopian Cityscape",
    "Gatsby's Gala",
    "Retro Diner at Midnight",
    "Pirate's Caribbean",
    "Sunset Safari",
    "Venetian Carnival",
    "Bali Rice Terrace",
    "Viking Longhouse",
    "Underground Cave System",
    "1940s Paris Cafe",
    "Medieval Castle",
    "Abstract Art Gallery",
    "Australian Outback",
    "Sunflower Field",
    "1960s Hippie Festival",
    "Lunar Base",
    "Haunted House",
    "Sherlock's Study",
    "Deep Sea Trench",
    "Ancient Egyptian Tomb",
    "Rustic Italian Vineyard",
    "Andean Alpaca Farm",
    "Fairy-tale Village",
    "Mad Scientist Laboratory",
    "Sakura Street Festival",
    "Futuristic Dubai",
    "Berlin Graffiti Alley",
    "Post-Apocalyptic Wasteland",
    "Jungle Treehouse",
    "Scottish Highland Ruins",
    "Ornate Indian Wedding",
    "Chicago Blues Club",
    "Grecian Olive Grove",
    "Prehistoric Cave Paintings",
    "Mexican Day of the Dead",
    "Moroccan Desert Camp",
    "Russian Winter Palace",
    "New Zealand Hobbit Shire",
    "Trans-Siberian Railway",
    "Arabian Nights",
    "Borealis Observatory",
    "Colonial Williamsburg",
    "Tuscan Sunflower Fields",
    "Wild West Saloon",
    "Brazilian Samba Parade",
    "Subterranean City",
    "Mystical Eastern Monastery",
    "Alaskan Glacial Fields",
    "Rooftop Garden",
    "Haunted Victorian Mansion",
    "1950s Americana",
    "Old West Gold Rush",
    "Mysterious Gypsy Caravan",
    "Roman Gladiator Arena",
    "Secret Garden",
    "Art Deco Miami",
    "Tropical Hawaiian Beach",
    "Gothic Cathedral",
    "South African Safari",
    "Retro Space Station",
    "Future Tokyo Streets",
    "Abandoned Amusement Park",
    "Provence Lavender Fields",
    "Renaissance Royal Court",
    "Rugged Rocky Mountains",
    "Old Irish Pub",
    "Cuban Street Festival",
    "Underwater Coral Reef",
    "Venice Canal at Dawn",
    "Neolithic Stone Circle",
    "New Orleans Jazz Bar",
    "Victorian London Fog",
    "French Riviera",
    "Roaring Twenties Chicago"
]);